### ISSUE TITLE
Library not loaded: @rpath/VirgilCryptoRatchet.framework/VirgilCryptoRatchet

### ISSUE THREAD

**Issue by ghanshyammansata** [VirgilSecurity/virgil-e3kit-x#10]
When I am trying to run my project on the device using VirgilE3kit downloaded using pods. Actually, I have created a new framework using VirgilE3Kit and that framework when I am using in my sample app it gives me the above error as dyld: Library not loaded: @rpath/VirgilCryptoRatchet.framework/VirgilCryptoRatchet
  Reason: image not found. Can you guide me on this?

**Comment by Ogerets** [comment]
Hi @ghanshyammansata! 
Please, check out sample I wrote trying to reproduce your issue 
https://github.com/Ogerets/wrapper-test

And this is simple wrapper framework, which depends on VirgilE3Kit and contains dummy class.
https://github.com/Ogerets/e3kit-wrapper

The sample depends on this wrapper and runs without errors. I managed all dependencies through cocoapods just like you mentioned. If sample doesn't help you resolve issue, then, please, tell, if you have some differences on language or platform.

**Comment by ghanshyammansata** [comment]
Hey @Ogerets, Thanks a ton to put efforts on replicating the issue. You are on the track but here you are providing files in the pods but I have to build a framework and publish to cocoapods and that to also should work on simulators as well. So just try to create a .framework file and link that file in WrapperTest project. I am also doing this but somehow I am not able to create a proper .framework file on my side using the e.g. given by you and trying to create an exact replica of the scenarios which I am facing.

**Comment by Ogerets** [comment]
If you want to link prebuilt binary, then, please, check out **Linking against prebuilt binaries** section in README. It contains instructions on adding all dependencies properly.

**Comment by Ogerets** [comment]
@ghanshyammansata Did you resolve your issue?

**Comment by ghanshyammansata** [comment]
I have created a project to replicate. Please open VirgilWrapper workspace and run the scheme VirgilWrapperTest on the simulator to replicate the issue. We are running a script to generate a framework file to support simulators so to generate a framework file, just run the scheme UniversalWrapper. 
[VirgilWrapper.zip](https://github.com/VirgilSecurity/virgil-e3kit-x/files/3187648/VirgilWrapper.zip)

**Comment by Ogerets** [comment]
@ghanshyammansata You cannot use binary of VirgilWrapper without its dependency binaries.  It's not about e3kit, it's about dependency management. 
So, to make your sample work you need to include dependency binaries of VirgilWrapper. I made your example work this way. I used carthage to dowload binaries, but you can do in your own way. Run 
```carthage update --platform ios``` inside VirgilWrapperTest folder and then project will run without errors.
[VirgilWrapper.zip](https://github.com/VirgilSecurity/virgil-e3kit-x/files/3187846/VirgilWrapper.zip)

**Comment by Ogerets** [comment]
As I understood, you want to distribute your sdk without code sharing. You can push sdk binary to pods. Then in Wrapper Test manage dependencies using pods. In this way you won't need to include all Wrapper dependencies in Wrapper Test yourself. Pods will do that for you.

**Comment by ghanshyammansata** [comment]
Yes @Ogerets, you have understood well. I want to distribute SDK without code sharing. I have tried above mention methods. But It didn't work for me. But I think I feel that there is an issue on our side while generating the framework. Let me recheck for this again and come back to you if any issues. Till then I am closing this issue. If any help required then I will reopen this issue again.

**Comment by ghanshyammansata** [comment]
Thanks a ton for your wonderful support.
