### ISSUE TITLE
Task failed with exit code 65:

### ISSUE THREAD

**Issue by ghost** [VirgilSecurity/virgil-e3kit-x#11]
`Building scheme "VirgilCryptoAPI iOS" in VirgilCryptoAPI.xcodeproj`
`This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/02/hcy55b4541l4z5xt8d2dc2j80000gp/T/carthage-xcodebuild.CaDLWf.log`

above errors, while trying to get virgil-e3kit- from Carthage

**Comment by Ogerets** [comment]
Hi, @bhooshanpatil
Can you, please, share error from xcodebuild log?

**Comment by ghost** [comment]
hey @Ogerets , 
as Virgil says [here](https://github.com/VirgilSecurity/virgil-e3kit-x#carthage), I'm in my first step to getting Virgil's all frameworks, but it keeps on failing to download, Here I'm sharing you a whole error log .
```
$ carthage update --platform iOS
*** Fetching virgil-e3kit-x
*** Fetching virgil-crypto-x
*** Fetching virgil-keyknox-x
*** Fetching virgil-pythia-x
*** Fetching virgil-sdk-x
*** Fetching virgil-cryptoapi-x
*** Checking out virgil-cryptoapi-x at "1.0.5"
*** Checking out virgil-keyknox-x at "0.3.0"
*** Checking out virgil-crypto-x at "3.2.2"
*** Checking out virgil-pythia-x at "0.4.0"
*** Checking out virgil-e3kit-x at "0.4.1"
*** Checking out virgil-sdk-x at "5.7.2"
*** xcodebuild output can be found in /var/folders/02/hcy55b4541l4z5xt8d2dc2j80000gp/T/carthage-xcodebuild.iphqoN.log
*** Downloading virgil-cryptoapi-x.framework binary at "v1.0.5"
*** Downloading virgil-crypto-x.framework binary at "v3.2.2"
*** Downloading virgil-sdk-x.framework binary at "v5.7.2"
***  Skipped installing virgil-cryptoapi-x.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
*** Downloading virgil-keyknox-x.framework binary at "v0.3.0"
*** Downloading virgil-pythia-x.framework binary at "v0.4.0"
***  Skipped installing virgil-sdk-x.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)."

    Falling back to building from the source
*** Downloading virgil-e3kit-x.framework binary at "v0.4.1"
*** Building scheme "VirgilCryptoAPI iOS" in VirgilCryptoAPI.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/ins/Desktop/virgil/Carthage/Checkouts/virgil-cryptoapi-x/VirgilCryptoAPI.xcodeproj -scheme VirgilCryptoAPI\ iOS -configuration Release -derivedDataPath /Users/ins/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/virgil-cryptoapi-x/1.0.5 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/02/hcy55b4541l4z5xt8d2dc2j80000gp/T/virgil-cryptoapi-x SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/ins/Desktop/virgil/Carthage/Checkouts/virgil-cryptoapi-x)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/02/hcy55b4541l4z5xt8d2dc2j80000gp/T/carthage-xcodebuild.iphqoN.log
```

**Comment by Ogerets** [comment]
This happens because your local swift version is 4.2 and fetched VirgilCryptoAPI and VirgilSDK SWIFT_VERSION=5.0. That's why Carthage throws error. For now you can fix this by changing your Cartfile line
```
github "VirgilSecurity/virgil-e3kit-x" ~> 0.4.1
```
 to 
```
github "VirgilSecurity/virgil-e3kit-x" ~> 0.4.1
github "VirgilSecurity/virgil-cryptoapi-x" "1.0.4"
github "VirgilSecurity/virgil-sdk-x" "5.7.1"
```
This will fetch not migrated to Swift 5 e3kit dependencies versions.
We are going to discuss with team more convenient swift 4.2 compatibility.

**Comment by Ogerets** [comment]
@bhooshanpatil Did my instructions help you resolve issue?

**Comment by ghost** [comment]
hey @Ogerets , yes your instructions have helped me a-lot , but **in integration i guess i'm not getting one required framework** ``` VSCCommon ```! please ref image attachment.
***
![2019-05-22](https://user-images.githubusercontent.com/25047864/58159888-06f4ea80-7c9b-11e9-8e83-bf9bb0917182.png)

**Comment by Ogerets** [comment]
@bhooshanpatil Did you add `VSCCommon` along with other frameworks as mentioned [here](https://github.com/VirgilSecurity/virgil-e3kit-x#carthage) to **Linked Frameworks and Libraries**? Please, try to re-add it. As said [here](https://stackoverflow.com/questions/32687105/framework-not-found-in-xcode) it can be Xcode issue.

**Comment by Ogerets** [comment]
@bhooshanpatil Did it work for you? Is there something else we can help you with?
