### ISSUE TITLE
[Suggestion] Combine EThree.findUsers and decrypt/encrypt methods

### ISSUE THREAD

**Issue by atereshkov** [VirgilSecurity/virgil-e3kit-x#30]
Hi there! Just a small improvement.

So on the latest beta version we’re using EThree.findUsers(with:forceReload:completion:), and in the completion block we can use decrypt/encrypt things. It makes +1 async nesting for the code, therefore my suggestion is just to **move the findUsers logic to the encrypt/decrypt functions** (they still require “users” array to be passed), so the SDK users can just call encrypt/decrypt functions instead of calling findUsers all the time. Or there are some hidden issues here that it’s done that way?

**Comment by Ogerets** [comment]
Hi, Alexander! 
This was done for the clarification of methods. Simply, `encrypt` should encrypt, nothing else hidden, which makes this method async suddenly. Also, not everybody work free with async methods, so then they could complain about wrong order of messages in their UI. Anyway, we will consider adding something like `findUsersThenEncrypt`. Thanks for your feedback. It's super helpful.

P.S. Here's some workarounds for you.
- You can use `EThree.findUsers(with:forceReload)` which returns `GenericOperation`. It allows you to add this operation to some queue or call it synchronously using `.startSync()` (Be aware of calling it not from main thread). This will remove nesting callbacks.
- There is `findCachedUsers` method, which uses only local storage of previously fetched users. You can build your app logic in such way, that at encrypt/decypt call there are always needed users in local storage. This will make your encrypt/decrypt code always synchronous.

**Comment by atereshkov** [comment]
Hey, Evgeny! Thanks for the answer and clarification!

I got your point and it definitely makes sense for some cases.

Anyway, feel free to close this issue as it's just a suggestion.

Speaking about finding users - I'm using .findUsers and seems (from the method description) like it should return the cards from the Virgil Cloud **or local storage if exists**. So I don't think .findCachedUsers would improve the flow for me as .findUsers already looks into the storage too.

**Comment by Ogerets** [comment]
> So I don't think .findCachedUsers would improve the flow for me as .findUsers already looks into the storage too.

You are right, findUsers looks locally before going to the cloud. The point is findCachedUsers will always run synchronously. No need to use callbacks and control the order of calling them. But it's all up to your app architecture. It's just one of the ways to implement.
