### ISSUE TITLE
[Suggestion] Open public API methods to be able to create mocks for unit testing

### ISSUE THREAD

**Issue by atereshkov** [VirgilSecurity/virgil-e3kit-x#31]
Would be great to have public API methods **open** instead of **public** to be able to create mocks for testing  purposes:

![image](https://user-images.githubusercontent.com/13171457/65763092-42149800-e12b-11e9-88ba-78402b925985.png)

**Comment by SanjoDeundiak** [comment]
Hi, @atereshkov. EThree class is not intended to be used as a superclass. For testing purposes you can create your own protocol for encryption and create two implementations: one using EThree and one with your mocks.

**Comment by atereshkov** [comment]
@SanjoDeundiak by doing so we can test only integration, and I wanted to test concrete implementation of the class that uses EThree. I would imagine we can achieve this behavior by adding a lot of abstractions and I personally don't think this would be better than just open public API.

EThree itself is already open for some reason :)

**Comment by SanjoDeundiak** [comment]
@atereshkov could you explain what exactly are you trying to test and why protocol approach doesn't work?

**Comment by atereshkov** [comment]
@SanjoDeundiak sure

```
protocol EncryptionServiceProtocol {
    func registerUser(with id: String) -> String, Error
    func encrypt(_ text: String) -> String, Error
    func decrypt(_ text: String) -> String, Error
}
```

And let's say we have concrete implementation for e3kit:

```
class VirgilEncryptionService: EncryptionServiceProtocol {
    
    private var e3kit: EThree?

    init(e3kit: EThree?) { 
        self.e3kit = e3kit
    }
    
    func registerUser(with id: String) -> String, Error {
        ...
        e3kit?.register { }
    }

    func encrypt(_ text: String) -> String, Error {
        e3kit.findUsers....
        e3kit.encrypt....
    }

    ....

}
```

I didn't say protocol approach doesn't work - in that particular case (code above) easier to just mock the e3kit instance than creating overhead by wrapping it to the abstract protocols. So your approach also would work of course, but I just personally want to be able to choose which one approach better to use in different cases. Currently we're not wrapping the e3kit instance and just using concrete implementation as shown above and to cover VirgilEncryptionService with the unit tests we have to wrap instance and change interfaces instead of just mocking e3kit instance.

**Comment by SanjoDeundiak** [comment]
@atereshkov we'll make public API open in next beta coming today or tomorrow.

**Comment by atereshkov** [comment]
Great, thank you!

**Comment by Ogerets** [comment]
@atereshkov You can check it out [0.7.0-beta7](https://github.com/VirgilSecurity/virgil-e3kit-x/releases/tag/0.7.0-beta7)
