### ISSUE TITLE
Assistance Needed: Unable to Checkout Virgil 4.0.1 in Xcode

### ISSUE THREAD

**Issue by keyurbhalodiya** [VirgilSecurity/virgil-e3kit-x#78]
I'm currently facing difficulties checking out version 4.0.1 of Virgil in Xcode for my project. I've attempted to integrate the latest release using Swift Package Manager (SPM), but it's failing with the following error:

`Couldn’t check out revision ‘40ae5231264c8f2d79354922fac15d96021aa8b5’.`

For more details, please refer to the attached screenshot.

![Screenshot 2023-12-18 at 12 21 51](https://github.com/VirgilSecurity/virgil-e3kit-x/assets/7112264/44050813-50b0-4731-a10f-1400bc468ef6)

Could you kindly assist me in resolving this issue?

Best regards,
Keyur

**Comment by SergeySeroshtan** [comment]
Will take a look.

**Comment by SergeySeroshtan** [comment]
Please follow this guide to install git-lfs on your system - https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage
